tooling(workflows): check for docs build errors
Because it apparently exits with 0 on error for whatever reason

diff --git a/.github/workflows/test_docs.yml b/.github/workflows/test_docs.yml
--- a/.github/workflows/test_docs.yml
+++ b/.github/workflows/test_docs.yml
@@ -33,4 +33,9 @@ jobs:
           npm link @discord-samba/typedoc-themes
 
       - name: Test building docs
-        run: node scripts/typedoc-runner
+        id: build_status
+        run: echo "##[set-output name=status;]$(node scripts/typedoc-runner | grep 'Error')"
+
+      - name: Fail if docs build produced errors
+        if: contains(steps.build_status.outputs.status, 'Error') != true
+        run: exit 1
